# Numpy Pratice Notebook

In [2]:
import numpy as np

In [3]:
myarr = np.array([[3, 6, 3, 7]], np.int64)

In [4]:
myarr

array([[3, 6, 3, 7]], dtype=int64)

In [5]:
myarr[0, 1]

6

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int64')

In [8]:
myarr[0, 1] = 45

In [9]:
myarr

array([[ 3, 45,  3,  7]], dtype=int64)

# Array Creation: Conversion from other Python structures

In [11]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [12]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [13]:
listarray.size

9

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.dtype

dtype('int32')

In [16]:
np.array({34,23.23})

array({34, 23.23}, dtype=object)

In [18]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
rng = np.arange(15)

In [21]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
lspace = np.linspace(1, 4, 4)

In [23]:
lspace

array([1., 2., 3., 4.])

In [24]:
emp  = np.empty((4, 6))

In [25]:
emp

array([[6.23042070e-307, 1.42417221e-306, 1.60219306e-306,
        7.56593017e-307, 7.56587584e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.33511018e-306, 6.23057689e-307,
        1.86921279e-306, 8.90098127e-307, 1.78020848e-306],
       [1.60219035e-306, 1.42418172e-306, 2.04712906e-306,
        7.56589622e-307, 1.11258277e-307, 8.90111708e-307]])

In [26]:
emp_like = np.empty_like(lspace)

In [27]:
emp_like

array([1., 2., 3., 4.])

In [28]:
ide = np.identity(45)

In [29]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [30]:
arr = np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr = arr.reshape(3, 33)

In [35]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [39]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr.shape

(3, 33)

# Numpy Axis

In [41]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [42]:
ar = np.array(x)

In [43]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
ar.sum(axis=0)

array([12,  8,  9])

In [45]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [46]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [47]:
ar.flat

In [50]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [51]:
ar.ndim

2

In [52]:
ar.size

9

In [53]:
ar.nbytes

36

In [55]:
one = np.array([1, 3, 5, 65, 76])

In [56]:
one.argmax()

4

In [57]:
one.argmin()

0

In [58]:
one.argsort()

array([0, 1, 2, 3, 4], dtype=int64)

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [60]:
ar.argmin()

8

In [61]:
ar.argmax()

6

In [64]:
ar.argmax(axis=0)

array([1, 1, 2], dtype=int64)

In [67]:
ar.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [63]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [68]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 0, 1, 7])

In [69]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 7]])

# Mathematical function in numpy

In [71]:
ar2 = np.array([[2, 4, 4],
       [4, 0, 6],
       [8, 1, 0]])

In [73]:
ar + ar2 # addition of two matrix

array([[ 3,  6,  7],
       [ 8,  5, 12],
       [ 8,  2,  7]])

In [75]:
ar * ar2 #multiplication

array([[ 2,  8, 12],
       [16,  0, 36],
       [ 0,  1,  0]])

In [77]:
np.sqrt(ar) #square root of matrix ar

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [0.        , 1.        , 2.64575131]])

In [78]:
ar.sum()

29

In [79]:
ar.max()

7

In [80]:
ar.min()

0

In [83]:
np.where(ar>5) #give the postion where the the ar element is > 5

(array([1, 2], dtype=int64), array([2, 2], dtype=int64))

In [84]:
type(np.where(ar>5))

tuple

In [86]:
np.count_nonzero(ar) #count the no. of non zero element

8

In [87]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 1, 2], dtype=int64))

In [88]:
ar[1, 2] = 0

In [89]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 1, 2], dtype=int64))

In [90]:
import sys

In [91]:
ch_ar = [0, 4, 55,2]

In [92]:
np_ar = np.array(ch_ar)

In [94]:
sys.getsizeof(1) * len(ch_ar)

112

In [95]:
np_ar.itemsize* np_ar.size

16